In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
one = np.ones(7, dtype=int)
one

array([1, 1, 1, 1, 1, 1, 1])

In [10]:
const1 = np.full(7, 7, dtype=float)
print(const1)

[7. 7. 7. 7. 7. 7. 7.]


In [7]:
const = np.full(9, 6.4)
print(const)

[6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.4]


In [30]:
x = np.array([1, 2.2, 3, 4.4, 5, 6.6] )

print(x)

[1.  2.2 3.  4.4 5.  6.6]


In [32]:
a=np.array([1, 2, 7.7 ,3 ,4, 5], dtype=int)
a

array([1, 2, 7, 3, 4, 5])

In [12]:
a[2] = 6.4
a

array([1, 2, 6, 3, 4, 5])

In [13]:
b=np.arange(1, 11, 2)
b

array([1, 3, 5, 7, 9])

In [45]:
z = np.linspace(0, 20, 5, dtype=int)
print(z)
y = np.linspace(0, 9, 9, dtype=int).reshape(3, 3)
# or
y = np.reshape(y, (3, 3))
print(y)

[ 0  5 10 15 20]
[[0 1 2]
 [3 4 5]
 [6 7 9]]


In [46]:
np.linspace(0, 1, 11)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

##  np.arange( start, stop, step)   , stop is exclusive
##  np.linspace(start, stop, num)   , stop is inclusive

MULTI-DIMENSIONAL ARRAY:

In [47]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
n=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
n[1, 1] = n[1, 1]*10
print(n)
print('\n')
print(n[2][2])
print('\n')
print(n[1])
n[1] = [7, 7, 7]
print('\n')
print(n)

[[ 1  2  9]
 [ 7 70  7]
 [ 7  8  9]]


9


[ 7 70  7]


[[1 2 9]
 [7 7 7]
 [7 8 9]]


In [53]:
print(n[:, 1])
print(n[:])
n[:, 2] = [9, 9, 9]
print(n) 

[2 7 8]
[[1 2 9]
 [7 7 7]
 [7 8 9]]
[[1 2 9]
 [7 7 9]
 [7 8 9]]


Randomly generated arrays:

In [54]:

np.random.seed(2)       # produces set numbers every time
np.random.rand(5, 2)    # produces random numbers(0-1) every time

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:

np.random.seed(2)       
np.random.randn(5, 2)       # n-std normal distribution    

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:

np.random.seed(2)       
100 * np.random.rand(5, 2)    

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [22]:

np.random.seed(2)       
np.random.randint(low=0, high=100, size=(5, 2))    

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations:

In [59]:
a = np.arange(5)
a = a+1
print(a)

[1 2 3 4 5]


In [62]:
print(a + 1)
print(a)

[2 3 4 5 6]
[1 2 3 4 5]


In [ ]:
b = ((10 + (a * 2))**2)/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
c = a + b
c

array([1.  , 2.44, 3.96, 5.56, 7.24])

Comparison operations:

In [64]:
print(a)
b = np.array([1, 0, 3, 0, 5])
print(b)

[1 2 3 4 5]
[1 0 3 0 5]


In [66]:
print(a >= 2)
print(a > b)

[False  True  True  True  True]
[False  True False  True False]


In [68]:
print(a[a<b])

[]


In [75]:
a > b

array([False, False,  True,  True,  True])

In [76]:
a[ a > b]

array([2, 3, 4])

Summarizing operations:

In [79]:
a

array([0, 1, 2, 3, 4])

In [78]:

a.min()

np.int64(0)

In [80]:
a.mean()

np.float64(2.0)

In [81]:
a.std()

np.float64(1.4142135623730951)

In [70]:
n

array([[1, 2, 9],
       [7, 7, 9],
       [7, 8, 9]])

In [71]:
n.sum()

np.int64(59)

In [72]:
print(n.mean())
print(n.mean(1))


6.555555555555555
[4.         7.66666667 8.        ]
